(part "TCM1-63AX-2+"
    (packageRef "TCM163AX2")
    (interface
        (port "1" (symbPinId 1) (portName "NOT_USED_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PRIMARY/GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PRIMARY_DOT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SECONDARY") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NOT_USED_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SECONDARY_DOT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "152")
    (property "Mouser_Part_Number" "139-TCM1-63AX-2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/TCM1-63AX-2%2b?qs=xZ%2FP%252Ba9zWqbCeM5gU814pw%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "TCM1-63AX-2+")
    (property "Description" "Audio Transformers / Signal Transformers TC XFMR / SURF MOUNT /    RoHS")
    (property "Datasheet_Link" "https://www.minicircuits.com/WebStore/dashboardPdf?model=TCM1-63AX-2%2B")
    (property "symbolName1" "TCM1-63AX-2+")
)
