(part "TCCH-80+"
    (packageRef "TCCH80")
    (interface
        (port "1" (symbPinId 1) (portName "RF-IN_&_DC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NOT_USED_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NOT_USED_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "139-TCCH-80")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/TCCH-80%2b?qs=xZ%2FP%252Ba9zWqbIZgt27nGgHg%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "TCCH-80+")
    (property "Description" "RF Choke")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/TCCH-80+.pdf")
    (property "symbolName1" "TCCH-80+")
)
