(part "SS54-HF"
    (packageRef "DIOM5025X220N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "750-SS54-HF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Comchip-Technology/SS54-HF?qs=GBLSl2AkiruU27AsKMcmrg%3D%3D")
    (property "Manufacturer_Name" "Comchip Technology")
    (property "Manufacturer_Part_Number" "SS54-HF")
    (property "Description" "DIODE SCHOTTKY 5A 40V SMA")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/SS54-HF.pdf")
    (property "symbolName1" "SS54-HF")
)
