(part "ERA-3+"
    (packageRef "ERA3")
    (interface
        (port "1" (symbPinId 1) (portName "RF_IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF-OUT_AND_DC-IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-ERA-3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/ERA-3%2b?qs=xZ%2FP%252Ba9zWqYUluriU41zUw%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "ERA-3+")
    (property "Description" "SMT MMIC, Linear, Gain Block, HBT Amplifier, DC to 3000 MHz, 50, Micro-X Style Package")
    (property "Datasheet_Link" "https://www.minicircuits.com/WebStore/dashboardPdf?model=ERA-3%2B")
    (property "symbolName1" "ERA-3+")
)
