(part "BFCN-5100+"
    (packageRef "BFCN5100")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUTPUT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GROUND_4") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_5") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GROUND_6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "139-BFCN-5100")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/BFCN-5100%2b?qs=xZ%2FP%252Ba9zWqYgAa562jLAEw%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "BFCN-5100+")
    (property "Description" "5.1GHz Center Band Pass Ceramic Filter 4 GHz 50Ohm 8-SMD Module")
    (property "Datasheet_Link" "https://www.minicircuits.com/WebStore/dashboard.html?model=BFCN-5100%2B")
    (property "symbolName1" "BFCN-5100+")
)
