(part "2480803-1"
    (packageRef "24808031")
    (interface
        (port "A5" (symbPinId 1) (portName "A5") (portType INOUT))
        (port "A9" (symbPinId 2) (portName "A9") (portType INOUT))
        (port "A12" (symbPinId 3) (portName "A12") (portType INOUT))
        (port "B5" (symbPinId 4) (portName "B5") (portType INOUT))
        (port "B9" (symbPinId 5) (portName "B9") (portType INOUT))
        (port "B12" (symbPinId 6) (portName "B12") (portType INOUT))
        (port "MH1" (symbPinId 7) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 8) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-2480803-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/2480803-1?qs=dbcCsuKDzFUIALFiru2Iew%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "2480803-1")
    (property "Description" "USB Connectors USB-C Charge Only Receptacle,6 Pin, Vertical, Short, 3u GF")
    (property "Datasheet_Link" "https://www.te.com/de/product-2480803-1.datasheet.pdf")
    (property "symbolName1" "2480803-1")
)
