(part "XFL4020-222MEB"
    (packageRef "XFL4020-222ME")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "994-XFL4020-222MEB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Coilcraft/XFL4020-222MEB?qs=VJjuEbE9QBO2bwonVBK1EA%3D%3D")
    (property "Manufacturer_Name" "COILCRAFT")
    (property "Manufacturer_Part_Number" "XFL4020-222MEB")
    (property "Description" "Fixed Inductors 2.2uH 20% 8A 23.5mOhms AEC-Q200")
    (property "Datasheet_Link" "https://www.coilcraft.com/pdfs/xfl4020.pdf")
    (property "symbolName1" "XFL4020-222MEB")
)
