(part "LM27762DSSR"
    (packageRef "SON50P200X300X80-13N-D")
    (interface
        (port "1" (symbPinId 1) (portName "PGOOD") (portType OUTPUT))
        (port "2" (symbPinId 2) (portName "FB+") (portType POWER))
        (port "3" (symbPinId 3) (portName "VIN") (portType POWER))
        (port "4" (symbPinId 4) (portName "GND") (portType GROUND))
        (port "5" (symbPinId 5) (portName "CP") (portType POWER))
        (port "6" (symbPinId 6) (portName "OUT-") (portType POWER))
        (port "7" (symbPinId 7) (portName "FB-") (portType POWER))
        (port "8" (symbPinId 8) (portName "EN-") (portType INPUT))
        (port "9" (symbPinId 9) (portName "C1-") (portType POWER))
        (port "10" (symbPinId 10) (portName "C1+") (portType POWER))
        (port "11" (symbPinId 11) (portName "OUT+") (portType POWER))
        (port "12" (symbPinId 12) (portName "EN+") (portType INPUT))
        (port "13" (symbPinId 13) (portName "PAD") (portType GROUND))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "595-LM27762DSSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM27762DSSR?qs=vcbl%252BK4rRlfEJcC9xQ80sA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM27762DSSR")
    (property "Description" "LDO Voltage Regulators Low-Noise Positive- and Negative-Output Integrated Switched Capacitor Plus LDO 12-WSON -40 to 85")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/lm27762.pdf")
    (property "symbolName1" "LM27762DSSR")
)
