(part "LT3042IMSE_PBF"
    (packageRef "SOP50P490X110-11N")
    (interface
        (port "1" (symbPinId 1) (portName "IN_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN/UV") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ILIM") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PGFB") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SET") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "OUTS") (portType INOUT))
        (port "10" (symbPinId 10) (portName "OUT") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-LT3042IMSE#PBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/LT3042IMSEPBF?qs=oahfZPh6IAKNLbWsEo0jgA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "LT3042IMSE#PBF")
    (property "Description" "LINEAR TECHNOLOGY - LT3042IMSE#PBF - LDO, ADJ, 0.2A, 0V-15V, MSOP-10")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/3042fb.pdf")
    (property "symbolName1" "LT3042IMSE_PBF")
)
