(part "PSA2-6+"
    (packageRef "SOT65P215X100-6N")
    (interface
        (port "1" (symbPinId 1) (portName "RF-IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RF-OUT_&_VD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-PSA2-6+")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/PSA2-6%2b?qs=ZcfC38r4PouoCLCeNyH1xw%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "PSA2-6+")
    (property "Description" "RF Amplifier SMT Low Noise Amplifier, DC - 7 GHz, 50?")
    (property "Datasheet_Link" "https://www.mouser.cn/datasheet/2/1030/PSA2_6_2b-3421589.pdf")
    (property "symbolName1" "PSA2-6+")
)
