(part "SKY13418-485LF"
    (packageRef "SKY13418485LF")
    (interface
        (port "1" (symbPinId 1) (portName "RF5") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RF3") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "V3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "V2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "N/C") (portType INOUT))
        (port "9" (symbPinId 9) (portName "RF2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "RF4") (portType INOUT))
        (port "11" (symbPinId 11) (portName "RF6") (portType INOUT))
        (port "12" (symbPinId 12) (portName "RF8") (portType INOUT))
        (port "13" (symbPinId 13) (portName "ANT") (portType INOUT))
        (port "14" (symbPinId 14) (portName "RF7") (portType INOUT))
        (port "15" (symbPinId 15) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "873-SKY13418-485LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Skyworks-Solutions-Inc/SKY13418-485LF?qs=aD6bdfC8ElNmIkWKGXNfog%3D%3D")
    (property "Manufacturer_Name" "Skyworks")
    (property "Manufacturer_Part_Number" "SKY13418-485LF")
    (property "Description" "RF Switch ICs 100-3000MHz SP8T IL .45dB Iso >31dB")
    (property "Datasheet_Link" "https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/701-800/SKY13418_485LF_201712F.pdf")
    (property "symbolName1" "SKY13418-485LF")
)
