(part "GALI-84+"
    (packageRef "GALI5")
    (interface
        (port "1" (symbPinId 1) (portName "RF-IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF-OUT_&_DC-IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-GALI-84")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/GALI-84%2b?qs=xZ%2FP%252Ba9zWqbD3SeeyZUsxg%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "GALI-84+")
    (property "Description" "RF Amplifier IC CATV, DBS, MMDS, Wireless LAN 0Hz ~ 6GHz SOT-89")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/Gali-84+.pdf?srsltid=AfmBOopZSkMNtZb47CBTWvUcGeXknsqF1jtkjMchs_3l04me5kYhi9jc")
    (property "symbolName1" "GALI-84+")
)
