(part "HFCG-3000+"
    (packageRef "HFCG3000")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GROUND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "139-HFCG-3000+")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/HFCG-3000%2b?qs=Znm5pLBrcAK7iw0r11flSw%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "HFCG-3000+")
    (property "Description" "Signal Conditioning LTCC High Pass Filter, 3400 - 13000 MHz")
    (property "Datasheet_Link" "https://www.minicircuits.com/WebStore/dashboardPdf?model=HFCG-3000%2B")
    (property "symbolName1" "HFCG-3000+")
)
