(part "PMA3-73-1W+"
    (packageRef "QFN51P300X300X89-13N")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RF-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "RF-OUT+VDD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_4") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NC_4") (portType INOUT))
        (port "11" (symbPinId 11) (portName "NC_5") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VIADJ") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "PMA3-73-1W+")
    (property "Description" "Mini-Circuits SMT MMIC, Power Amplifier, 300 MHz to 7500 MHz, 50ohm, 3x3 mm QFN Style Package")
    (property "Datasheet_Link" "https://www.minicircuits.com/WebStore/dashboard.html?model=PMA3-73-1W%2B")
    (property "symbolName1" "PMA3-73-1W+")
)
