(part "OPA1632DGNR"
    (packageRef "SOP65P490X110-9N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN-") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOCM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "V+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT-") (portType INOUT))
        (port "6" (symbPinId 6) (portName "V-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "ENABLE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN+") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-OPA1632DGNR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA1632DGNR?qs=7nS3%252BbEUL6t46Xk02kKOHg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA1632DGNR")
    (property "Description" "Fully Differential I/O Audio Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/OPA1632")
    (property "symbolName1" "OPA1632DGNR")
)
