(part "ADA4940-2ACPZ-RL"
    (packageRef "QFN50P400X400X80-25N-D")
    (interface
        (port "1" (symbPinId 1) (portName "–IN1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "+FB1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+VS1_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "+VS1_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "–FB2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "+IN2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "–IN2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "+FB2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "+VS2_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "+VS2_2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VOCM2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "+OUT2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "–OUT2") (portType INOUT))
        (port "14" (symbPinId 14) (portName "%DISABLE2%") (portType INOUT))
        (port "15" (symbPinId 15) (portName "–VS2_1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "–VS2_2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "VOCM1") (portType INOUT))
        (port "18" (symbPinId 18) (portName "+OUT1") (portType INOUT))
        (port "19" (symbPinId 19) (portName "–OUT1") (portType INOUT))
        (port "20" (symbPinId 20) (portName "%DISABLE1%") (portType INOUT))
        (port "21" (symbPinId 21) (portName "–VS1_1") (portType INOUT))
        (port "22" (symbPinId 22) (portName "–VS1_2") (portType INOUT))
        (port "23" (symbPinId 23) (portName "–FB1") (portType INOUT))
        (port "24" (symbPinId 24) (portName "+IN1") (portType INOUT))
        (port "25" (symbPinId 25) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADA4940-2ACPZ-R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADA4940-2ACPZ-RL?qs=BpaRKvA4VqHPFnyO4tWbXA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADA4940-2ACPZ-RL")
    (property "Description" "Differential Amplifiers Sub 10M W ADC Driver for PULSAR Family")
    (property "Datasheet_Link" "https://www.mouser.in/datasheet/2/609/ADA4940-1_4940-2-878284.pdf")
    (property "symbolName1" "ADA4940-2ACPZ-RL")
)
