(part "TPS62150RGTR"
    (packageRef "QFN50P300X300X100-17N-D")
    (interface
        (port "1" (symbPinId 1) (portName "SW_1") (portType INPUT))
        (port "2" (symbPinId 2) (portName "SW_2") (portType INPUT))
        (port "3" (symbPinId 3) (portName "SW_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "FB") (portType INOUT))
        (port "6" (symbPinId 6) (portName "AGND") (portType GROUND))
        (port "7" (symbPinId 7) (portName "FSW") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DEF") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SS/TR") (portType INOUT))
        (port "10" (symbPinId 10) (portName "AVIN") (portType INOUT))
        (port "11" (symbPinId 11) (portName "PVIN_1") (portType INOUT))
        (port "12" (symbPinId 12) (portName "PVIN_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EN") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VOS") (portType INOUT))
        (port "15" (symbPinId 15) (portName "PGND_1") (portType GROUND))
        (port "16" (symbPinId 16) (portName "PGND_2") (portType GROUND))
        (port "17" (symbPinId 17) (portName "THERMAL_PAD") (portType GROUND))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "595-TPS62150RGTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS62150RGTR?qs=gXEV9p%2FxLgee1dYSWoqQIw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS62150RGTR")
    (property "Description" "317V 1A Step-Down Converter with DCS-Control in 3x3 QFN package")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tps62150")
    (property "symbolName1" "TPS62150RGTR")
)
